# needed to run from windows
# application: renovault
# version: wpfromstarterproject

runtime: php55
api_version: 1
threadsafe: yes

env_variables:
  
  DEV_OR_DIST: DEV

  # mollie.com
  MOLLIE_COM_API_KEY_DEV: test_6Ppjcfe7w4h6Cd
  MOLLIE_COM_API_KEY_DIST: live_sSGvTwR9DfhQz

  MYSQL_DSN_PROD_USER: mysql:unix_socket=/cloudsql/zappp:europe-west3:dbjobhip
  MYSQL_USER_PROD_USER: zappp
  MYSQL_PASSWORD_PROD_USER: VF9VJTmDn23RErxvSYxV

  MYSQL_DSN_DEV_USER: mysql:host=127.0.0.1
  MYSQL_USER_DEV_USER: zappp
  MYSQL_PASSWORD_DEV_USER: VF9VJTmDn23RErxvSYxV

handlers:

- url: /js
  static_dir: js
  secure: always

- url: /node_modules
  static_dir: node_modules
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /fonts
  static_dir: fonts
  secure: always

- url: /images
  static_dir: images
  secure: always

# api
- url: /api/(.*)$
  script: /api/index.php
  secure: always

# front handler (matches anything)
- url: /(.*)$
  script: index.php 
  secure: always
